version: '3.7'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
    networks:
      - proxy-tier

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: acme
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=prefix+yourdomaindotcomproxy@gmail.com
    networks:
      - proxy-tier

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    environment:
      - VIRTUAL_HOST=jenkins.yourdomain.com
      - LETSENCRYPT_HOST=jenkins.yourdomain.com
      - LETSENCRYPT_EMAIL=prefix+yourdomaindotcomproxy@gmail.com
      - VIRTUAL_PORT=8080
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    depends_on:
      - nginx-proxy
    networks:
      - proxy-tier

networks:
  proxy-tier:

volumes:
  certs:
  vhost:
  html:
  acme:
