services:
  i2p-router:
    container_name: i2p-router
    image: geti2p/i2p:latest
    platform: linux/amd64
    restart: always
    ports:
      - 4444:4444
      - 6668:6668
      - 7657:7657
      - ${EXT_PORT}:12345
      - ${EXT_PORT}:12345/udp
    volumes:
      - i2phome:/i2p/.i2p
      - i2ptorrents:/i2psnark

volumes:
  i2phome:
  i2ptorrents:
